### ISSUE TITLE
Add convenience method for getting xarray dims and coords

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/useq-schema#13]
It would be nice to be able to easily fill in an xarrray array's dims and coords based on a sequence. Or even to be able to directly create an xarray DataArrray from the sequence which will then be filled in via MDA.

Basic approach could be something like this

```python
from typing import List, Dict
def sequence_to_xarray_dims_coords(sequence: MDASequence) -> [List, Dict]:
    mapping = {"t": "time_plan", "c": "channels", "z": "z_plan", "p": "positions"}
    coords = {}
    dims = []
    for ax in axis_order:
        try:
            if ax == "c":
                coords['C'] = [c.config for c in sequence.channels]
            else:
                coords[ax.upper()] = list(getattr(sequence, mapping[ax]))
            dims.append(ax.upper())
        except AttributeError:
            pass
    dims.extend(['Y', "X"])
    return dims, coords
```

**Comment by tlambert03** [comment]
I'm afraid i feel like this is a bit out of scope for useq-schema.  It would make sense as a helper function in pymmcore-plus perhaps, but probably is best just implemented as a one-off function wherever you need it.  If you have one you use  routinely and want to contribute it at pymmcore-plus, please open a PR there.  Thanks!
