### ISSUE TITLE
Add mehtod for getting `axis_order` only from axes used in events

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/useq-schema#17]
Very handy when trying to prepare a datastructure for receiving MDA data as noted here: https://github.com/tlambert03/pymmcore-plus/pull/29#discussion_r679267817

A quick function that gives this is: 

```python
    def get_axis_order(seq: MDASequence) -> Tuple[str]:
        """Get the axis order using only axes that are present in events."""
        event = next(seq.iter_events())
        event_axes = list(event.index.keys())
        return tuple(a for a in seq.axis_order if a in event_axes)
```

**Comment by ianhi** [comment]
Biggest struggle is what to call thing this method. Should this just override the default axis order, or should it be named something different?

**Comment by tlambert03** [comment]
this was added a while back as `used_axes`

https://github.com/pymmcore-plus/useq-schema/blob/a904ae3b4185bd920c05ec1319971974be32882b/src/useq/_mda_sequence.py#L314-L317
