### ISSUE TITLE
WellPlatePlan selected_wells field_validator

### ISSUE THREAD

**Issue by fdrgsp** [pymmcore-plus/useq-schema#183]
@tlambert03 I think the reason for which when we do:

`useq.WellPlatePlan(plate=6, a1_center_xy=(0,0), selected_wells=())`

or 

`useq.WellPlatePlan(plate=6, a1_center_xy=(0,0), selected_wells=None)` 

we get all the well selected is because in the [WellPlatePlan selected_wells field_validator](https://github.com/pymmcore-plus/useq-schema/blob/3eea067cfbc922bcd602c18d164c4be446f0d062/src/useq/_plate.py#L240) we run `plate.indices(value)` which in absence of `value` returns the entire well indices.

Not sure what's the best way to fix that, if in the `validator` itself, in [plate.indices](https://github.com/pymmcore-plus/useq-schema/blob/3eea067cfbc922bcd602c18d164c4be446f0d062/src/useq/_plate.py#L85) or maybe in [_expression_repr](https://github.com/pymmcore-plus/useq-schema/blob/3eea067cfbc922bcd602c18d164c4be446f0d062/src/useq/_plate.py#L444) methods...

**Comment by tlambert03** [comment]
The intention was to select all wells by default, do you want to change it to select no wells by default?
