### ISSUE TITLE
Check SLMImage `exposure` input values

### ISSUE THREAD

**Issue by hinderling** [pymmcore-plus/useq-schema#210]
Currently even negative values are allowed, 
```python
event = MDAEvent(slm_image=SLMImage(data=True,exposure=-999))
mmc.mda.run([event])
--> runs
```

where as this is checked for camera exposure:
```python
event = MDAEvent(exposure=-99)
--> validation error for MDAEvent
```

Not sure if this needs to be checked, because negative values are allowed on device level (Polygon1000, genericSLM):
```python
mmc.setSLMExposure(slm_dev,-999)
print(mmc.getSLMExposure(slm_dev))
--> -999.0
```

**Comment by tlambert03** [comment]
good catch!  pydantic makes this easy, let's copy this pattern:

https://github.com/pymmcore-plus/useq-schema/blob/4b42d1e3ec21351b4865121e167a26d40eb2555f/src/useq/_mda_event.py#L192
