### ISSUE TITLE
Add a way of generating groups of events

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/useq-schema#40]
I'm thinking about how to implement a `keep shutter open` option for pymmcore-plus and finding that there is not a convenient way to interpret the `for event in seq.iter_events()` to check for how many events we should keep the shutter open.

I think there needs to be a way to implement generating a chunk of events that match some criteria - e.g. give me the next set of events that have `channel=='FITC'`. 

One way to do this maybe would be to introduce a new object `MDAEventGroup` that could serve as the intermediate, or perhaps to allow MDASequences to contain MDASequences.

The simpler workaround that I'm currently going with is to expand on the `iter_` methods with a new `iter_chunked` method that goes like so:

```python
def iter_chunked(seq: MDASequence, over: str) -> Iterator[List[MDAEvent]]:
    """
    Generate events in chunks where only the given *over* index changes

    Parameters
    ----------
    seq : MDASequence
    over : str
        The index keys over which to allow grouping. E.g. 'z' to return
        all events in the z stack for a given time point, position and channel.

    yields
    ------
    chunk : list of events
    """

    over = over.lower()

    def extract_index(event):
        return tuple(event.index.get(key) for key in event.index.keys() if key not in over)

    events = seq.iter_events()
    e = next(events)
    cur_chunk = extract_index(e)

    chunk = [e]
    for e in events:
        if extract_index(e) == cur_chunk:
            chunk.append(e)
        else:
            yield chunk
            chunk = [e]
            cur_chunk = extract_index(e)
    if len(chunk) > 0:
        # ensure we always return all events
        yield chunk
```

**Comment by tlambert03** [comment]
yeah, we do definitely need something like this.  I like these ideas here, but want to ponder the API a bit.
We also need this for (e.g.) fast sequence acquisitions in micro-manager.
There, however, an argument could be made that the actual nature of chunking is going to vary a bit depending on the exact consumer of the sequence of events.  so the thing I guess I want to answer here is whether there really is a universal/general enough thing that this should be in useq-schema, as opposed to just telling the consumer (e.g. pymmcore-plus) to take the whole sequence (with `list(seq.iter_events())`) and re-arrange/chunk it as needed for things like sequence acquisition or keeping shutters open .

**Comment by tlambert03** [comment]
> as opposed to just telling the consumer (e.g. pymmcore-plus) to take the whole sequence (with list(seq.iter_events())) and re-arrange/chunk it as needed for things like sequence acquisition or keeping shutters open .

as I think about this more, i think this is actually the right way to go.  I don't think this belongs in useq-schema, I think it belongs in the consumer application.  See for example, the `event_iterator` added for supporting hardware sequencing in pymmcore-plus:

https://github.com/pymmcore-plus/pymmcore-plus/blob/e1962bc8fb36d02eefeced215b63f200e1bd3b9c/src/pymmcore_plus/mda/_engine.py#L87-L107

**Comment by tlambert03** [comment]
@ianhi, feel free to request this to be reopened if the above isn't clear.  But to summarize, I think it's responsibility of the consumer (be it pymmcore-plus) or any other library to rechunk an iterable of events.  I think the signature of such a method should be:

```python
def iterator_wrapper(events: Iterable[MDAEvent]) -> Iterator[MDAEvent | Any]: ...
```

note that `MDASequence` is just one form of `Iterable[MDAEvent]` ... the signature above is more general.  See the link in the previous comment for an example
