### ISSUE TITLE
task: emit warnings on extra kwargs

### ISSUE THREAD

**Issue by tlambert03** [pymmcore-plus/useq-schema#77]
we can't use pydantic's extra='forbid' setting, since it makes it very hard to add new fields without breaking backwards compatibility ... but it would be nice to have warnings to show that a kwarg is unrecognized

**Comment by fdrgsp** [comment]
closed by #78

**Comment by ieivanov** [comment]
I wanted to follow up on this. We are back to `extra="ignore"` - what was the motivation for this? I occasionally would make a simple mistake such as using `channel` rather than `channels` and my acquisition will not run as expected. Is there something we can do differently?
